fix: no-codegen output file name warning
This avoids errors based on output file name when the `--no-codegen`
command is passed to `crystal build` since it shouldn't be necessary
to specify an output file if no file will be created anyway.

Example:

$ crystal build --no-codegen  example/example.cr
Error: can't use `example` as output filename because it's a directory