Fix missing param count in compilation error msg
A private macro definition with one parameter which is called with no
parameter resulted in a compiler error message where the "expected"
count was missing. From the original issue:

```crystal
private macro foo(x)
end

foo # Error: wrong number of arguments for macro 'foo' (given 0, expected )
```

The error was caused by a statement that rejected private macros, which
resulted in `all_arguments_sizes` being empty.

The removed code was added in cabb0219a6ecda8777d16bf2ffe511381f74c8d7.
The affected specs are green, so I assume there's no regression without
that statement.

Fixes https://github.com/crystal-lang/crystal/issues/13872